RestRoom/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RestRoom.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='/app/')),
    url(r'^app/', include('app.urls', namespace='app')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

app/urls.py
from django.conf.urls import patterns, url

from app.views import classicLogin, ClassicSignUP, explore, Home, Login, Logout, peopleNearby, updatelatlng


urlpatterns = patterns('',
                       url(r'^$', Home.as_view(), name='home'), 
                       url(r'^login/$', Login, name='login'),
                       url(r'^classiclogin/$', classicLogin, name='classiclogin'),
                       url(r'^logout/$', Logout, name='logout'),
                       url(r'^home/$', Home.as_view(), name='home'),
                       url(r'^signup', ClassicSignUP, name='signup'),
                       url(r'^updatelatlng/$', updatelatlng, name='updatelatlng'),
                       url(r'^explore/$', explore, name='explore'),
                       url(r'^peoplenearby/$', peopleNearby, name='peoplenearby'),
                       )

app/templates/explore.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom | Explore</title>

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
   <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

    <!-- Custom styles for this template -->
    <style type="text/css">

          /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 50px;
        padding-bottom: 20px;
      }

      html, body{
        height: 100%;
        margin: 0px;
        padding: 0px
      }

        #map-canvas{
          height: 800px;
          width: 100%;
        }
      .controls {
          margin-top: 16px;
          border: 1px solid transparent;
          border-radius: 2px 0 0 2px;
          box-sizing: border-box;
          -moz-box-sizing: border-box;
          height: 32px;
          outline: none;
          box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }

        #pac-input {
 /*         background-color: #fff;
          padding: 0 11px 0 13px;
          width: 400px;
          font-family: Roboto;
          font-size: 15px;
          font-weight: 300;
          text-overflow: ellipsis;*/
        }

        #pac-input:focus {
          border-color: #4d90fe;
          margin-left: -1px;
          padding-left: 14px;  /* Regular padding-left + 1. */
          width: 401px;
        }

        .pac-container {
          font-family: Roboto;
        }

        #type-selector {
          color: #fff;
          background-color: #4d90fe;
          padding: 5px 11px 0px 11px;
        }

        #type-selector label {
          font-family: Roboto;
          font-size: 13px;
          font-weight: 300;
        }

      #target {
        width: 345px;
      }
    .container {
      width: 100%;
    }

    </style>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hello, {{user.first_name}} {{user.last_name}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <!-- <input type="text" id="pac-input" class="controls"> -->
            </div>
            <img src="http://i.imgur.com/67I6mTq.gif" style="display:none" id="gif-loader">
            <img src="http://provennutritionforkids.com/wp-content/uploads/2012/10/Green-CheckMark.png" style="display:none" id="gif-done">
            <a href="{% url 'app:home' %}" class="btn btn-success" id="update-location">Home</a>
            <a href="{% url 'app:logout' %}" class="btn btn-success">Logout</a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
<!--       <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
      <div id="map-canvas"></div>
      <p>
          <label for="amount">Explore others(50 Km increments):</label>
          <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
      </p>
      <div id="slider"></div>
    </div>

    <script>

    var latitude, longitude, map, infowindows = [], markers = [];

    var data = {{data|safe}};

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    $(document).ready(function(){


      $(function() {
        $( "#slider" ).slider({
          value:200,
          min: 0,
          max: 20000,
          step: 50,
          slide: function( event, ui ) {
            $( "#amount" ).val(ui.value + ' KM');

            $.ajax({
            url: "{% url 'app:peoplenearby' %}",
            type: 'POST',
            data: {csrfmiddlewaretoken:csrftoken,
                   distance: ui.value
                 },
            success: function(data) {
              console.log(data);
              $('#gif-loader').hide();
              $('#gif-done').show();  
              $( "#gif-done" ).fadeOut(1000);
              if(data.status){
                putMarkers({}, JSON.parse(data.data));
              } 
              else{
                alert('Opps!!')
              }  


            },
            error: function(e) {
              console.log('error');
              console.log(e.toString());
            }
          });


          }
        });
        $( "#amount" ).val($( "#slider" ).slider( "value" ) + ' Km');
      });

    });



    function clearMarkersWindows() {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
        infowindows[i].close();
      }
    }

    function moreinfo(marker, infowindow){

      var f = function(){
        console.log('Guess what, someone clicked me!')
        content = '<div><strong>' +  marker.custom_info.first_name + ' ' + marker.custom_info.last_name + '</strong><br>' + marker.custom_info.address + '</div>';
        infowindow.setContent(content);
        infowindow.open(map, marker);
      }
      return f;

    }

    function putMarkers(foo, loc_data){
      console.log('Running putMarkers');

      clearMarkersWindows();
      markers = [];
      infowindows = [];

      if(loc_data === undefined){
        loc_data = data;
      }

      console.log(JSON.stringify(loc_data));

      var bounds = new google.maps.LatLngBounds();

      for(var i=0; i < loc_data.length; i++){
        var loc = loc_data[i];
        var geolocate = new google.maps.LatLng(loc.lat, loc.lang);
        var marker = new google.maps.Marker({
           map: map,
           anchorPoint: new google.maps.Point(0, -29),
           title: 'Click for more info!'
        });
        marker.setPosition(geolocate);
        marker.setVisible(true);
        var infowindow = new google.maps.InfoWindow();

        marker.custom_info = {first_name: loc.first_name,
                              last_name: loc.last_name,
                              address: loc.address,
                              infowindow: infowindow
                            }
        
        //closure call
        google.maps.event.addListener(marker, 'click', moreinfo(marker, infowindow));
        
        infowindow.setContent('<div>' +  loc.first_name + '</div>');
        infowindow.open(map, marker);
        markers.push(marker); 
        infowindows.push(infowindow);
        bounds.extend(geolocate);
      }

      map.fitBounds(bounds);
      map.setCenter(bounds.getCenter());

    }


    function initialize() {

      console.log('Running initialize');

      map = new google.maps.Map(document.getElementById('map-canvas'), {
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: new google.maps.LatLng({{user.lat}}, {{user.lang}}),
        zoom: 14
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
    google.maps.event.addDomListener(window, 'load', putMarkers);

    </script>

  </body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom | Home</title>

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

    <!-- Custom styles for this template -->
    <style type="text/css">

          /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 50px;
        padding-bottom: 20px;
      }

      html, body{
        height: 100%;
        margin: 0px;
        padding: 0px
      }

        #map-canvas{
          height: 800px;
          width: 100%;
        }
      .controls {
          margin-top: 16px;
          border: 1px solid transparent;
          border-radius: 2px 0 0 2px;
          box-sizing: border-box;
          -moz-box-sizing: border-box;
          height: 32px;
          outline: none;
          box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }

        #pac-input {
 /*         background-color: #fff;
          padding: 0 11px 0 13px;
          width: 400px;
          font-family: Roboto;
          font-size: 15px;
          font-weight: 300;
          text-overflow: ellipsis;*/
        }

        #pac-input:focus {
          border-color: #4d90fe;
          margin-left: -1px;
          padding-left: 14px;  /* Regular padding-left + 1. */
          width: 401px;
        }

        .pac-container {
          font-family: Roboto;
        }

        #type-selector {
          color: #fff;
          background-color: #4d90fe;
          padding: 5px 11px 0px 11px;
        }

        #type-selector label {
          font-family: Roboto;
          font-size: 13px;
          font-weight: 300;
        }

      #target {
        width: 345px;
      }
    .container {
      width: 100%;
    }

    </style>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hello, {{user.first_name}} {{user.last_name}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <!-- <input type="text" id="pac-input" class="controls"> -->
            </div>
            <img src="http://i.imgur.com/67I6mTq.gif" style="display:none" id="gif-loader">
            <img src="http://provennutritionforkids.com/wp-content/uploads/2012/10/Green-CheckMark.png" style="display:none" id="gif-done">
            <a href="#" class="btn btn-success" id="update-location">Update location</a>
            <a href="#" class="btn btn-success" id="detect-location" tooltip="Detect and save location">Detect & save</a>
            <a href="#" class="btn btn-success" id="explore">Explore</a>
            <a href="{% url 'app:logout' %}" class="btn btn-success">Logout</a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
      <input id="pac-input" class="controls" type="text" placeholder="Search Box">
      <div id="map-canvas"></div>
    </div>

    <script>

    var latitude, longitude, map, infowindow, marker;

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function saveLocation(){

        if(marker !== undefined){

          console.log('Current location is Lat: ' + marker.position.k + ' Long: ' + marker.position.D);
          console.log('Now updating....')

          $('#gif-loader').show()

          $.ajax({
            url: "{% url 'app:updatelatlng' %}",
            type: 'POST',
            data: {csrfmiddlewaretoken:csrftoken,
                   lat: marker.position.k,
                   lng: marker.position.D,
                   placename: marker.custom_info.placename,
                   address: marker.custom_info.address
                 },
            success: function(data) {
              console.log(data);
              latitude = marker.position.k;
              longitude = marker.position.D;
              $('#gif-loader').hide();
              $('#gif-done').show();  
              $( "#gif-done" ).fadeOut(1000);

            },
            error: function(e) {
              console.log('error');
              console.log(e.toString());
            }
          });
        }
        else{

          alert('Oops! no marker found on the map. Please select a location first.')

        }

      }


    $(document).ready(function(){

      $('#explore').click(function(){
        if(latitude && longitude){
          window.location = "{% url 'app:explore' %}";
        }
        else{
          alert('You must save a location first to explore other people nearby.')
        }

      });

      $('#update-location').click(saveLocation);

      $('#detect-location').click(function(){
        SetLocation();
      })

    });

    function updateinfoWindow(latlng, callback, geolocate){

      var geocoder = new google.maps.Geocoder();

      geocoder.geocode({
            "latLng": latlng
        }, function (results, status) {
            console.log(results, status);
            if (status == google.maps.GeocoderStatus.OK) {
                console.log(results);
                var address_components = results[0].address_components;
                var placeName = address_components[0].long_name;
                
                var address = '';
                address += results[0].formatted_address || '';

                marker.custom_info.placename = placeName;
                marker.custom_info.address = address;

                infowindow.setContent('<div><strong>' + placeName + '</strong><br>' + address);
                infowindow.open(map, marker);
                if(callback){
                  callback(geolocate);
                }
            }
        });

    }

    function SetDbLocation(){

      console.log('Running SetDbLocation');
      marker.setVisible(false);
      infowindow.close();

      latitude = {{user.lat}};
      longitude = {{user.lang}};

      var geolocate = new google.maps.LatLng(latitude, longitude);

      marker.custom_info.placename = '{{user.placename}}';
      marker.custom_info.address = '{{user.address}}';

      marker.setPosition(geolocate);
      marker.setVisible(true);
      if (marker.custom_info.address || marker.custom_info.placename){
        infowindow.setContent('<div><strong>' +  marker.custom_info.placename + '</strong><br>' + marker.custom_info.address);
        infowindow.open(map, marker);
      }
      
      // updateinfoWindow(geolocate);
      // infowindow.open(map, marker); 
      map.setCenter(geolocate);
      map.setZoom(17)

    }


    function setLocationOnFailure(){

          var geolocate = new google.maps.LatLng(23.42154524119965, 79.00593125);
          marker.setPosition(geolocate);
          marker.setVisible(true);
          var callback = function(geolocate){
            map.setCenter(geolocate);
            map.setZoom(17)
            saveLocation();
          }
          updateinfoWindow(geolocate, callback, geolocate);



    }


    function SetLocation(){

        console.log('Running SetLocation');

        marker.setVisible(false);
        infowindow.close();

        if(!!navigator.geolocation) {
                
                    navigator.geolocation.getCurrentPosition(function(position) {

                      console.log(position);

                        var latitude = position.coords.latitude;
                        var longitude = position.coords.longitude;
                    
                        var geolocate = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                        
                        marker.setPosition(geolocate);
                        marker.setVisible(true);
                        var callback = function(geolocate){
                          //Database query is too fast for Geocoder
                          map.setCenter(geolocate);
                          map.setZoom(17)
                          saveLocation();
                        }
                        updateinfoWindow(geolocate, callback, geolocate);

                    }, function(err){
                        if(err.code == 1){
                          alert("As you're not allowing us to read your location, you'll have to find it yourself using either using the search box or drag the marker around.");
                          setLocationOnFailure();
                        }
                      
                    });
        }
        else{

          alert("Guess what, geolocation is not possible on your broswer. You'll have to find it yourself using either using the search box or drag the marker around.")
          setLocationOnFailure()

         }

    }


    function initialize() {

      console.log('Running initialize');


      map = new google.maps.Map(document.getElementById('map-canvas'), {
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        zoom: 17
      });

      var input = /** @type {HTMLInputElement} */(
          document.getElementById('pac-input'));
      map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.bindTo('bounds', map);

      infowindow = new google.maps.InfoWindow();

      marker = new google.maps.Marker({
        map: map,
        anchorPoint: new google.maps.Point(0, -29),
        draggable:true,
        animation: google.maps.Animation.DROP,
        title:"Drag me to exact location!"
      });

      marker.custom_info = {placename:'', address: ''};

      google.maps.event.addListener(marker, 'dragend', function () {

        var lat = marker.position.k;
        var lng = marker.position.D;

        console.log('Guess what, someone dragged me!')
        var latlng = new google.maps.LatLng(lat, lng);
        updateinfoWindow(latlng);

      });

      google.maps.event.addListener(autocomplete, 'place_changed', function() {

        infowindow.close();
        marker.setVisible(false);
        var place = autocomplete.getPlace();
        if (!place.geometry) {
          return;
        }

        console.log(place.geometry.viewport);

        // If the place has a geometry, then present it on a map.
        if (place.geometry.viewport) {
          map.fitBounds(place.geometry.viewport);
        } else {
          map.setCenter(place.geometry.location);
          map.setZoom(17);  // Why 17? Because it looks good.
        }
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);

        var address = '';

        address +=  place.formatted_address || '';

        marker.custom_info.placename = place.name;
        marker.custom_info.address = address;

        infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
        infowindow.open(map, marker);

      });

    }

    google.maps.event.addDomListener(window, 'load', initialize);
    {% if user.lat == 0 and user.lang == 0 %}
    google.maps.event.addDomListener(window, 'load', SetLocation);
    {% else %}
    google.maps.event.addDomListener(window, 'load', SetDbLocation);
    {% endif%}

    </script>

  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<!-- /*    <style type="text/css">
        .col-md-offset-3 {
            margin: 20% auto !important;
            float: none;
        }
    </style>*/ -->
  </head>

  <body>

    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="loginform" class="form-horizontal" role="form" action="{% url 'app:classiclogin' %}" method="POST">
                        {% csrf_token %} 
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">                                        
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                    </div>
                                    
                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <input type="submit" class="btn btn-success" value="Login">
                                      <a id="btn-fblogin" href="{% url 'social:begin' 'facebook' %}?next={%url 'app:home' %}" class="btn btn-primary">Login with Facebook</a>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            Sign Up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     

                        </div>                     
                    </div>  
        </div>
        <div id="signupbox" style="display:none; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">Sign Up</div>
                            <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
                        </div>  
                        <div class="panel-body" >
                            <form id="signupform" class="form-horizontal" role="form" action="{% url 'app:signup'%}" method="POST">
                            {% csrf_token %}
                                
                                <div id="signupalert" style="display:none" class="alert alert-danger">
                                    <p>Error:</p>
                                    <span></span>
                                </div>
                                  
                                <div class="form-group">
                                    <label for="email" class="col-md-3 control-label">Email</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="email" placeholder="Email Address">
                                    </div>
                                </div>
                                    
                                <div class="form-group">
                                    <label for="firstname" class="col-md-3 control-label">First Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="first_name" placeholder="First Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="lastname" class="col-md-3 control-label">Last Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-md-3 control-label">Password</label>
                                    <div class="col-md-9">
                                        <input type="password" class="form-control" name="password" placeholder="Password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <!-- Button -->                                        
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" class="btn btn-info"><i class="icon-hand-right" value="Sign Up">
                                        <span style="margin-left:8px;">or</span>  
                                    </div>
                                </div>
                                
                                <div style="border-top: 1px solid #999; padding-top:20px"  class="form-group">
                                    
                                    <div class="col-md-offset-3 col-md-9">
                                        <a href="{% url 'social:begin' 'facebook' %}?next={%url 'app:home' %}" id="btn-fbsignup" class="btn btn-primary"><i class="icon-facebook"></i>Sign Up with Facebook</a>
                                    </div>                                           
                                        
                                </div>
                                
                                
                                
                            </form>
                         </div>
                    </div>

               
               
                
         </div> 
    </div>






    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  </body>
</html>